### ISSUE TITLE
Cron Jobs

### ISSUE THREAD

**Issue by saadmerie** [flowdee/wp-udemy#10]
Hello flowdee, I have another issue with the plugin, this time the cron jobs
check this:
![cron](https://cloud.githubusercontent.com/assets/26535566/24186375/139da64a-0ee9-11e7-92ef-16e5d53dced4.JPG)
it says that the next cron job is in 1970
that is causing an issue that the cache is not refreshing automatically, and cause "low memory" errors in php, so I have to delete the cache manually every day.
I have a cron-job external service (cron-job.org) 
and it is doing well, if that can help I can use it to trigger the cache deletion. 

also, I tried to contact you on "hello" email, but you may didn't get the email, do you have another contact method?

Regards

**Comment by flowdee** [comment]
Thanks for letting me know. I'll have to take a look into the cache renewal issue.

Feel free to contact me via https://coder.flowdee.de/contact/ 👍

**Comment by flowdee** [comment]
Can you please try the latest version of the master here @saadmerie ?

I fixed the datetime formatting. The cache renewal should be working fine before as well.

**Comment by saadmerie** [comment]
It worked
![cron](https://cloud.githubusercontent.com/assets/26535566/24191291/705f6f2c-0efc-11e7-88c2-81828aee97b0.JPG)

but this is UTC time, right?

**Comment by flowdee** [comment]
Yep possible, but actually doesn't matter regarding the cache renewal functionality.

**Comment by flowdee** [comment]
Finally released v1.0.7 including this fix. Should be available in a few minutes.
