### ISSUE TITLE
Grid template is not being displayed properly

### ISSUE THREAD

**Issue by flowdee** [flowdee/wp-udemy#29]
https://kryptonitewp.com/demo/wp-udemy/

<img width="938" alt="Bildschirmfoto 2020-04-30 um 09 49 36" src="https://user-images.githubusercontent.com/2278756/80685733-edbe0600-8ac7-11ea-9220-e826b7b39b42.png">

**Comment by flowdee** [comment]
https://secure.helpscout.net/conversation/1098455817/21606?folderId=407329

**Comment by flowdee** [comment]
https://secure.helpscout.net/conversation/1151052842/24149/

**Comment by webdj-agency** [comment]
Fixed.please check out @flowdee

**Comment by flowdee** [comment]
Fixed with v1.1.5
